name: 🐞 Bug report
description: Create a report to help us improve our project
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please carefully read our code of conduct before creating a bug report
        👉 https://www.schroedinger-hat.org/code-of-conduct

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a way for us to be able to reproduce the problem you ran into.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: additonal
    attributes:
      label: Additional context
      description: If applicable, add any other context about the problem here
