import "@/styles/globals.css"

import { Inter } from "next/font/google"

import NextAuthProvider from "@/context/NextAuthProvider"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
}

interface LayoutInterface {
  children: React.ReactNode
}

export default async function RootLayout({ children }: LayoutInterface) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}
